image: atlassian/default-image:latest

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            runs-on:
              - 'linux.arm64'
            caches:
              - maven
            script:
              - echo "Building the project for arm64 architecture using Java 17"
              - ./mvnw -Pnative package
            artifacts:
              - target/**